---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Values.mysql.name}}
  namespace: {{.Values.namespace}}-db
spec:
  selector:
    matchLabels:
      app: {{.Values.mysql.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.mysql.name}}
    spec:
      containers:
      - image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.version }}"
        name: {{.Values.mysql.name}}
        env:
          {{- range .Values.mysql.env}}
          - name: "{{.name}}"
            value: "{{.value}}"
          {{- end}}
          {{- range .Values.mysql.secretEnv}}
          - name: "{{.name}}"
            valueFrom:
              secretKeyRef:
                name: "{{.secretKeyRef.name}}"
                key: "{{.secretKeyRef.key}}"
          {{- end}}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
